spring:
  application:
    name: consumer
  http:
    multipart:
      max-file-size: 30mb
      max-request-size: 300mb
server:
  port: 8086
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8082/eureka/